### ISSUE TITLE
Error connecting to Hue Bridge: Incorrect data return from Hue API

### ISSUE THREAD

**Issue by bruesche** [iobroker-community-adapters/ioBroker.hue-extended#180]
Hi,

Update to Deconz Version 2.13.1 gives the warning 'Error connecting to Hue Bridge: Incorrect data return from Hue API. Already retried 15x so far. Try again in 1 minute..'. Lights are not working anymore. Adapter 'Deconz' works fine. 

Please have a look at the warning/error with hue-extended adapter. 

Thx

**Comment by realwax** [comment]
hue-extended.0 | 2021-11-19 14:18:46.719 | warn | Error connecting to Hue Bridge: Incorrect data return from Hue API. Already retried 10x so far. Try again in 1 minute..
-- | -- | -- | --

Hi, same here. Adapter goes green and then red again stating not connection since the latest update to version 2.13.02. Though they reach and speak with each other as key renewal works. Must be api change related. 

Thank you!

**Comment by EdgarM73** [comment]
same here, with update to deconz 2.13.1 this adapter is not working anymore

**Comment by EdgarM73** [comment]
switched back to deconz 2.12.06 and it works fine.

**Comment by kopierschnitte** [comment]
This could lead to problems for new installations / "out of the box experience". Would be great if someone could investigate this...

**Comment by ANB777** [comment]
#185 should resolve this issue by adding [alarmsystems](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/alarmsystems/) introduced in deconz 2.13.x.
